/**
 * VIRALPULSE AI - EXPORT & REPORT UTILITIES
 */

export function downloadJsonReport(analysisData) {
  const jsonString = `data:text/json;charset=utf-8,${encodeURIComponent(
    JSON.stringify(analysisData, null, 2)
  )}`;
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute('href', jsonString);
  downloadAnchor.setAttribute(
    'download',
    `virality_report_${analysisData.metadata.title.toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 25) || 'video'}.json`
  );
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

export function copyReportSummary(analysisData) {
  const text = `
🎯 VIRALPULSE AI VIRALITY AUDIT REPORT
=========================================
📹 Title: "${analysisData.metadata.title || 'Untitled'}"
🔥 Virality Score: ${analysisData.overallScore} / 100 (${analysisData.performanceTier})
📈 Projected Reach: ${analysisData.predictedViews} Views (${analysisData.viralProbability} viral odds)
⚡ Hook Power: ${analysisData.metrics.hookStrength}/100
⏱️ Retention / Pacing: ${analysisData.metrics.pacingRetention}/100
💬 Engagement Velocity: ${analysisData.metrics.engagementVelocity}/100
🎵 Trend / Audio Synergy: ${analysisData.metrics.trendAudio}/100
🏷️ SEO / Hashtag Power: ${analysisData.metrics.seoOptimization}/100

💡 Top AI Hook Recommendation:
"${analysisData.hookSuggestions[0]?.hook || ''}"

Generated by ViralPulse AI (https://viralpulse.ai)
  `.trim();

  return navigator.clipboard.writeText(text);
}
